// server/games-data.js
module.exports = {
  categories: [
    { id: 'romance', label: 'Romance' },
    { id: 'personality', label: 'Personality' },
    { id: 'fun', label: 'Fun' },
    { id: 'occasions', label: 'Special Occasions' },
  ],
  games: [
    // ── ROMANCE ──
    {
      id: 'first_impressions',
      category: 'romance',
      title: 'First impressions',
      icon: '😊',
      cost: 150,
      premium: false,
      type: 'compare',
      questions: [
        { id: 'fi1', q: 'What was going through your mind when we first met?' },
        { id: 'fi2', q: 'What was the first thing you noticed about me?' },
        { id: 'fi3', q: 'When did you realize you liked me?' },
        { id: 'fi4', q: 'What was our best early date?' },
        { id: 'fi5', q: 'What first made you laugh about me?' },
      ],
    },
    {
      id: 'our_story',
      category: 'romance',
      title: 'Our story',
      icon: '📖',
      cost: 175,
      premium: true,
      type: 'compare',
      questions: [
        { id: 'os1', q: "What's the chapter of us you'd reread?" },
        { id: 'os2', q: 'What was a turning point for us?' },
        { id: 'os3', q: "What's a small moment that meant a lot?" },
        { id: 'os4', q: 'What do you hope our next chapter holds?' },
        { id: 'os5', q: 'How would you title our story?' },
      ],
    },
    // ── PERSONALITY ──
    {
      id: 'favorite_hobbies',
      category: 'personality',
      title: 'Favorite hobbies',
      icon: '🧩',
      cost: 100,
      premium: false,
      type: 'guess',
      questions: [
        { id: 'fh1', q: "My partner's favorite way to relax is..." },
        { id: 'fh2', q: 'My partner could talk for hours about...' },
        { id: 'fh3', q: 'A hobby my partner wants to try is...' },
        { id: 'fh4', q: "My partner's ideal weekend involves..." },
        { id: 'fh5', q: "My partner's guilty pleasure is..." },
      ],
    },
    {
      id: 'creative_side',
      category: 'personality',
      title: 'Creative side',
      icon: '🎨',
      cost: 150,
      premium: false,
      type: 'guess',
      questions: [
        { id: 'cs1', q: "If my partner made art, it'd be..." },
        { id: 'cs2', q: "My partner's taste in music is..." },
        { id: 'cs3', q: 'My partner expresses themselves best by...' },
        { id: 'cs4', q: 'A creative dream my partner has is...' },
        { id: 'cs5', q: "My partner's style in one word..." },
      ],
    },
    // ── FUN ──
    {
      id: 'winter_fun',
      category: 'fun',
      title: 'Winter fun',
      icon: '🧶',
      cost: 100,
      premium: false,
      type: 'compare',
      questions: [
        { id: 'wf1', q: 'Best cozy winter activity for us?' },
        { id: 'wf2', q: 'Hot chocolate or coffee?' },
        { id: 'wf3', q: 'Ideal snow day plan?' },
        { id: 'wf4', q: 'Favorite winter memory together?' },
        { id: 'wf5', q: 'Dream winter trip?' },
      ],
    },
    {
      id: 'summer_fun',
      category: 'fun',
      title: 'Summer fun',
      icon: '🌴',
      cost: 125,
      premium: false,
      type: 'compare',
      questions: [
        { id: 'sf1', q: 'Beach day or road trip?' },
        { id: 'sf2', q: 'Best summer food?' },
        { id: 'sf3', q: 'Our perfect summer evening?' },
        { id: 'sf4', q: 'A summer adventure we should take?' },
        { id: 'sf5', q: 'Favorite warm-weather memory of us?' },
      ],
    },
    // ── SPECIAL OCCASIONS ──
    {
      id: 'birthday_party',
      category: 'occasions',
      title: 'Birthday party',
      icon: '🎁',
      cost: 150,
      premium: false,
      type: 'guess',
      questions: [
        { id: 'bp1', q: "My partner's dream birthday is..." },
        { id: 'bp2', q: 'The gift my partner secretly wants...' },
        { id: 'bp3', q: "My partner's favorite cake flavor..." },
        { id: 'bp4', q: 'How my partner likes to celebrate...' },
        { id: 'bp5', q: 'A surprise my partner would love...' },
      ],
    },
    {
      id: 'holidays',
      category: 'occasions',
      title: 'Holidays',
      icon: '🎄',
      cost: 125,
      premium: true,
      type: 'compare',
      questions: [
        { id: 'h1', q: 'Favorite holiday to spend together?' },
        { id: 'h2', q: 'Best holiday tradition we have?' },
        { id: 'h3', q: 'A new tradition we should start?' },
        { id: 'h4', q: 'Favorite holiday food?' },
        { id: 'h5', q: 'Dream holiday destination together?' },
      ],
    },
  ],
};
