// server/games-data.js
// "How well do you know each other" format:
// each question is a personal TOPIC. In a game you (1) answer each about
// YOURSELF, then (2) guess what your partner answered about THEMSELVES.
// Questions are multiple-choice (options[]) with the occasional open-ended one (open:true).
module.exports = {
  categories: [
    { id: 'romance', label: 'Romance' },
    { id: 'personality', label: 'Personality' },
    { id: 'fun', label: 'Fun' },
    { id: 'occasions', label: 'Special Occasions' },
    { id: 'party', label: 'Party' },
    { id: 'deep', label: 'Deep Talks' },
    { id: 'longdistance', label: 'Long Distance' },
    { id: 'spicy', label: 'Spicy 🌶️' },
  ],
  games: [
    // ── ROMANCE ──
    {
      id: 'first_impressions',
      category: 'romance',
      title: 'First impressions',
      icon: '😊',
      cost: 150,
      questions: [
        { id: 'fi1', q: 'Your favorite memory of us', open: true },
        { id: 'fi2', q: 'The moment you knew you liked me', open: true },
        { id: 'fi3', q: 'Your favorite thing about our relationship', options: ['How we laugh together', 'Feeling totally comfortable', 'Our deep talks', 'The adventures', 'How we support each other'] },
        { id: 'fi4', q: 'A dream date you’d take me on', options: ['Cozy night in', 'Fancy dinner', 'Weekend getaway', 'Outdoor adventure', 'Concert or show'] },
        { id: 'fi5', q: 'What makes you feel most loved', options: ['Words of affirmation', 'Quality time', 'Physical touch', 'Acts of service', 'Gifts'] },
      ],
    },
    {
      id: 'love_languages',
      category: 'romance',
      title: 'Love languages',
      icon: '💕',
      cost: 150,
      questions: [
        { id: 'll1', q: 'Your main love language', options: ['Words of affirmation', 'Quality time', 'Physical touch', 'Acts of service', 'Receiving gifts'] },
        { id: 'll2', q: 'How you most like to receive affection', options: ['Hugs & cuddles', 'Sweet words', 'Little surprises', 'Undivided attention', 'Helpful gestures'] },
        { id: 'll3', q: 'A small gesture that melts you', options: ['A forehead kiss', 'A handwritten note', 'Holding hands', 'A good-morning text', 'Bringing me food'] },
        { id: 'll4', q: 'What makes you feel appreciated', options: ['A genuine thank you', 'Being listened to', 'A thoughtful surprise', 'Help without asking', 'Being bragged about'] },
        { id: 'll5', q: 'Your idea of quality time', options: ['Cuddling & talking', 'A shared hobby', 'A night out', 'Traveling somewhere', 'Just being together'] },
      ],
    },
    {
      id: 'date_night',
      category: 'romance',
      title: 'Date night',
      icon: '🍷',
      cost: 125,
      questions: [
        { id: 'dn1', q: 'Your ideal date night', options: ['Movie & takeout', 'Dinner out', 'Game night', 'Stargazing', 'Dancing'] },
        { id: 'dn2', q: 'A dream vacation for the two of us', options: ['Tropical beach', 'European cities', 'Mountain cabin', 'Road trip', 'Theme park'] },
        { id: 'dn3', q: 'A restaurant you always crave', open: true },
        { id: 'dn4', q: 'Movie genre for a cozy night in', options: ['Rom-com', 'Horror', 'Action', 'Animated', 'Documentary'] },
        { id: 'dn5', q: 'Your perfect lazy Sunday with me', options: ['Sleeping in', 'Brunch out', 'Netflix marathon', 'A long walk', 'Cooking together'] },
      ],
    },
    {
      id: 'our_future',
      category: 'romance',
      title: 'Our future',
      icon: '🔮',
      cost: 175,
      premium: true,
      questions: [
        { id: 'of1', q: 'Where you want us to live someday', options: ['Cozy city apartment', 'Suburban house', 'Cabin in nature', 'By the beach', 'Somewhere abroad'] },
        { id: 'of2', q: 'Something you really want us to do together', open: true },
        { id: 'of3', q: 'Your dream for us in five years', open: true },
        { id: 'of4', q: 'A tradition you want us to start', options: ['Weekly date night', 'A yearly trip', 'Sunday breakfasts', 'Movie nights', 'Holiday rituals'] },
        { id: 'of5', q: 'How you picture our perfect home', options: ['Cozy & warm', 'Modern & sleek', 'Full of plants', 'Lots of art', 'Big & open'] },
      ],
    },

    // ── PERSONALITY ──
    {
      id: 'favorite_things',
      category: 'personality',
      title: 'Favorite things',
      icon: '🧩',
      cost: 100,
      questions: [
        { id: 'ft1', q: 'Your comfort food', options: ['Pizza', 'Mac & cheese', 'Ramen', 'Ice cream', 'Burgers'] },
        { id: 'ft2', q: 'Your favorite season', options: ['Spring', 'Summer', 'Fall', 'Winter'] },
        { id: 'ft3', q: 'Your go-to drink order', options: ['Coffee', 'Tea', 'Soda', 'Smoothie', 'Just water'] },
        { id: 'ft4', q: 'Your favorite way to relax', options: ['Watching TV', 'Reading', 'Napping', 'A hot bath', 'Going outside'] },
        { id: 'ft5', q: 'Your happy place', open: true },
      ],
    },
    {
      id: 'deep_dive',
      category: 'personality',
      title: 'Deep dive',
      icon: '🌊',
      cost: 150,
      questions: [
        { id: 'dd1', q: 'Your biggest fear', options: ['Heights', 'Bugs/spiders', 'Being alone', 'Failure', 'The dark'] },
        { id: 'dd2', q: 'Something you’re really proud of', open: true },
        { id: 'dd3', q: 'A goal you’re chasing right now', open: true },
        { id: 'dd4', q: 'What stresses you out most', options: ['Work / school', 'Money', 'Being late', 'Conflict', 'Clutter'] },
        { id: 'dd5', q: 'What you do to recharge', options: ['Alone time', 'Time with me', 'Sleep', 'Exercise', 'A hobby'] },
      ],
    },
    {
      id: 'quirks',
      category: 'personality',
      title: 'Quirks & habits',
      icon: '🤪',
      cost: 100,
      questions: [
        { id: 'qk1', q: 'Your most used emoji', options: ['😂', '❤️', '😭', '🙄', '😎'] },
        { id: 'qk2', q: 'A weird little habit you have', open: true },
        { id: 'qk3', q: 'Your guilty pleasure', options: ['Reality TV', 'Junk food', 'Online shopping', 'Long naps', 'Doomscrolling'] },
        { id: 'qk4', q: 'Something that instantly annoys you', options: ['Loud chewing', 'Slow walkers', 'Being interrupted', 'Messiness', 'Being ignored'] },
        { id: 'qk5', q: 'Your hidden talent', open: true },
      ],
    },
    {
      id: 'screen_sound',
      category: 'personality',
      title: 'Screen & sound',
      icon: '🎬',
      cost: 125,
      questions: [
        { id: 'ss1', q: 'Your favorite movie genre', options: ['Comedy', 'Action', 'Romance', 'Horror', 'Sci-fi / Fantasy'] },
        { id: 'ss2', q: 'A music genre you love most', options: ['Pop', 'Hip-hop', 'R&B', 'Rock', 'Indie / Alt'] },
        { id: 'ss3', q: 'A show you could rewatch forever', open: true },
        { id: 'ss4', q: 'Your karaoke go-to song', open: true },
        { id: 'ss5', q: 'Ideal way to enjoy a story', options: ['Movies', 'TV series', 'Books', 'Podcasts', 'Video games'] },
      ],
    },

    // ── FUN ──
    {
      id: 'this_or_that',
      category: 'fun',
      title: 'This or that',
      icon: '🎲',
      cost: 100,
      questions: [
        { id: 'tt1', q: 'Beach or mountains', options: ['Beach', 'Mountains'] },
        { id: 'tt2', q: 'Sweet or savory', options: ['Sweet', 'Savory'] },
        { id: 'tt3', q: 'Night owl or early bird', options: ['Night owl', 'Early bird'] },
        { id: 'tt4', q: 'Coffee or tea', options: ['Coffee', 'Tea'] },
        { id: 'tt5', q: 'Cats or dogs', options: ['Cats', 'Dogs'] },
      ],
    },
    {
      id: 'silly_questions',
      category: 'fun',
      title: 'Silly questions',
      icon: '🤡',
      cost: 100,
      questions: [
        { id: 'sq1', q: 'A superpower you’d choose', options: ['Flying', 'Invisibility', 'Time travel', 'Mind reading', 'Teleportation'] },
        { id: 'sq2', q: 'Three things for a desert island', open: true },
        { id: 'sq3', q: 'Your spirit animal', options: ['Cat', 'Dog', 'Owl', 'Wolf', 'Dolphin'] },
        { id: 'sq4', q: 'A dream dinner guest, dead or alive', open: true },
        { id: 'sq5', q: 'Your role in a zombie apocalypse', options: ['The leader', 'The fighter', 'The medic', 'The strategist', 'First to go 😅'] },
      ],
    },
    {
      id: 'foodies',
      category: 'fun',
      title: 'Foodies',
      icon: '🍜',
      cost: 125,
      questions: [
        { id: 'fd1', q: 'Your favorite cuisine', options: ['Italian', 'Mexican', 'Asian', 'Comfort / American', 'Mediterranean'] },
        { id: 'fd2', q: 'A food you secretly can’t stand', open: true },
        { id: 'fd3', q: 'Your best midnight snack', options: ['Chips', 'Ice cream', 'Cereal', 'Leftovers', 'Cookies'] },
        { id: 'fd4', q: 'Sweet tooth or salty cravings', options: ['Sweet tooth', 'Salty snacks', 'Both equally'] },
        { id: 'fd5', q: 'Your signature dish', open: true },
      ],
    },
    {
      id: 'wanderlust',
      category: 'fun',
      title: 'Wanderlust',
      icon: '✈️',
      cost: 150,
      questions: [
        { id: 'wl1', q: 'Top of your travel bucket list', open: true },
        { id: 'wl2', q: 'The best trip you’ve ever taken', open: true },
        { id: 'wl3', q: 'Window or aisle seat', options: ['Window', 'Aisle'] },
        { id: 'wl4', q: 'Dream destination type', options: ['Big city', 'Tropical beach', 'Historic Europe', 'Nature & wildlife', 'Mountains'] },
        { id: 'wl5', q: 'Road trip or resort', options: ['Road trip', 'Resort'] },
      ],
    },

    // ── SPECIAL OCCASIONS ──
    {
      id: 'birthday_wishes',
      category: 'occasions',
      title: 'Birthday wishes',
      icon: '🎁',
      cost: 150,
      questions: [
        { id: 'bw1', q: 'Your dream birthday', options: ['Big party', 'Intimate dinner', 'A trip away', 'Quiet day in', 'A fun activity'] },
        { id: 'bw2', q: 'A gift you secretly want', open: true },
        { id: 'bw3', q: 'Your favorite cake flavor', options: ['Chocolate', 'Vanilla', 'Red velvet', 'Funfetti', 'Cheesecake'] },
        { id: 'bw4', q: 'How you like to celebrate', options: ['With everyone', 'Just us two', 'Family only', 'Low-key', 'Go all out'] },
        { id: 'bw5', q: 'A surprise you’d absolutely love', open: true },
      ],
    },
    {
      id: 'holidays',
      category: 'occasions',
      title: 'Holidays',
      icon: '🎄',
      cost: 125,
      questions: [
        { id: 'hd1', q: 'Your favorite holiday', options: ['Christmas', 'Halloween', 'Thanksgiving', 'New Year', 'Valentine’s'] },
        { id: 'hd2', q: 'Best holiday food', open: true },
        { id: 'hd3', q: 'A holiday tradition you love', open: true },
        { id: 'hd4', q: 'Dream holiday destination', options: ['Snowy cabin', 'Tropical escape', 'Big city lights', 'Home & cozy', 'Visiting family'] },
        { id: 'hd5', q: 'Gift giving or receiving', options: ['Giving', 'Receiving', 'Both!'] },
      ],
    },
    {
      id: 'milestones',
      category: 'occasions',
      title: 'Milestones',
      icon: '🥂',
      cost: 175,
      premium: true,
      questions: [
        { id: 'ms1', q: 'How you’d celebrate an anniversary', options: ['Romantic dinner', 'A getaway', 'Recreate our first date', 'Gifts & cards', 'Quiet day together'] },
        { id: 'ms2', q: 'A milestone you’re looking forward to', open: true },
        { id: 'ms3', q: 'Your ideal way to mark good news', options: ['Go out to celebrate', 'Tell everyone', 'Treat ourselves', 'A quiet toast', 'A special meal'] },
        { id: 'ms4', q: 'How you like to be congratulated', options: ['A big hug', 'Kind words', 'A gift', 'A celebration', 'A sweet message'] },
        { id: 'ms5', q: 'Your dream celebration', open: true },
      ],
    },
    {
      id: 'seasons',
      category: 'occasions',
      title: 'Seasons',
      icon: '🍂',
      cost: 100,
      questions: [
        { id: 'se1', q: 'Your favorite season', options: ['Spring', 'Summer', 'Fall', 'Winter'] },
        { id: 'se2', q: 'Best cozy winter activity', options: ['Movies under blankets', 'Hot cocoa', 'Building a snowman', 'Baking', 'Reading by the fire'] },
        { id: 'se3', q: 'Your ideal summer day', options: ['Beach day', 'Pool & BBQ', 'Road trip', 'Festival / concert', 'Lazy in the AC'] },
        { id: 'se4', q: 'A fall tradition you love', options: ['Pumpkin patch', 'Cozy sweaters', 'Halloween', 'Apple picking', 'Warm drinks'] },
        { id: 'se5', q: 'Spring or autumn', options: ['Spring', 'Autumn'] },
      ],
    },

    // ── PARTY (single-round prompt packs: both answer, reveal & compare) ──
    {
      id: 'would_you_rather',
      category: 'party',
      title: 'Would you rather',
      icon: '🤔',
      cost: 100,
      format: 'party',
      questions: [
        { id: 'wyr1', q: 'Would you rather…', options: ['Read minds', 'See the future'] },
        { id: 'wyr2', q: 'Would you rather…', options: ['Beach holiday', 'Mountain cabin'] },
        { id: 'wyr3', q: 'Would you rather…', options: ['Never be cold', 'Never be hot'] },
        { id: 'wyr4', q: 'Would you rather…', options: ['Always early', 'Always late'] },
        { id: 'wyr5', q: 'Would you rather…', options: ['Cook together', 'Order in'] },
        { id: 'wyr6', q: 'Would you rather…', options: ['Stay in', 'Go out'] },
        { id: 'wyr7', q: 'Would you rather…', options: ['Sunrise person', 'Sunset person'] },
        { id: 'wyr8', q: 'Would you rather…', options: ['Live by the sea', 'Live in the city'] },
      ],
    },
    {
      id: 'would_you_rather_spicy',
      category: 'party',
      title: 'Would you rather: us',
      icon: '💞',
      cost: 125,
      format: 'party',
      questions: [
        { id: 'wru1', q: 'Would you rather…', options: ['Forehead kisses', 'Hand holding'] },
        { id: 'wru2', q: 'Would you rather…', options: ['Little spoon', 'Big spoon'] },
        { id: 'wru3', q: 'Would you rather…', options: ['Surprise date', 'Planned date'] },
        { id: 'wru4', q: 'Would you rather…', options: ['Love notes', 'Long hugs'] },
        { id: 'wru5', q: 'Would you rather…', options: ['Slow dance', 'Movie cuddle'] },
        { id: 'wru6', q: 'Would you rather…', options: ['Breakfast in bed', 'Late-night talks'] },
      ],
    },
    {
      id: 'never_have_i_ever',
      category: 'party',
      title: 'Never have I ever',
      icon: '🙊',
      cost: 100,
      format: 'party',
      questions: [
        { id: 'nh1', q: 'Pulled an all-nighter', options: ['I have', 'I never'] },
        { id: 'nh2', q: 'Been on a blind date', options: ['I have', 'I never'] },
        { id: 'nh3', q: 'Sung karaoke in public', options: ['I have', 'I never'] },
        { id: 'nh4', q: 'Traveled solo', options: ['I have', 'I never'] },
        { id: 'nh5', q: 'Cried at a movie', options: ['I have', 'I never'] },
        { id: 'nh6', q: 'Gone skinny dipping', options: ['I have', 'I never'] },
        { id: 'nh7', q: 'Broken a bone', options: ['I have', 'I never'] },
        { id: 'nh8', q: 'Stayed up to watch the sunrise', options: ['I have', 'I never'] },
      ],
    },

    // ════════ ROMANCE (+3) ════════
    {
      id: 'love_languages_deep',
      category: 'romance',
      title: 'Love languages deep-dive',
      icon: '💞',
      cost: 150,
      questions: [
        { id: 'll1', q: 'The way you most feel my love', options: ['Words', 'Quality time', 'Touch', 'Acts of service', 'Gifts'] },
        { id: 'll2', q: 'A small gesture that melts you', open: true },
        { id: 'll3', q: 'How you most like to show love', options: ['Saying it', 'Doing things', 'Being close', 'Giving things', 'Making time'] },
        { id: 'll4', q: 'Words you never get tired of hearing', open: true },
        { id: 'll5', q: 'When do you feel closest to me', options: ['Lazy mornings', 'Deep talks', 'Adventures', 'Quiet nights', 'Just texting'] },
      ],
    },
    {
      id: 'little_things',
      category: 'romance',
      title: 'The little things',
      icon: '🧸',
      cost: 125,
      questions: [
        { id: 'lt1', q: 'A tiny habit of mine you adore', open: true },
        { id: 'lt2', q: 'Your favorite way we say goodnight', options: ['A call', 'Texts', 'Voice notes', 'A photo', 'Just "night 💜"'] },
        { id: 'lt3', q: 'The everyday thing you miss most', open: true },
        { id: 'lt4', q: 'My most kissable feature', options: ['Forehead', 'Cheeks', 'Nose', 'Hands', 'Lips'] },
        { id: 'lt5', q: 'A sound or smell that reminds you of me', open: true },
      ],
    },
    {
      id: 'song_and_senses',
      category: 'romance',
      title: 'Our song & senses',
      icon: '🎶',
      cost: 125,
      questions: [
        { id: 'ss1', q: 'Our song, if we had to pick one', open: true },
        { id: 'ss2', q: 'A scent that feels like "us"', options: ['Fresh laundry', 'Coffee', 'Rain', 'Vanilla', 'The ocean'] },
        { id: 'ss3', q: 'The taste of a perfect date', options: ['Pizza', 'Sushi', 'Tacos', 'Dessert first', 'Home-cooked'] },
        { id: 'ss4', q: 'A song that makes you think of me', open: true },
        { id: 'ss5', q: 'Your favorite kind of hug', options: ['Bear hug', 'Back hug', 'Slow sway', 'Forehead tuck', 'Tackle hug'] },
      ],
    },

    // ════════ PERSONALITY (+3) ════════
    {
      id: 'how_my_brain_works',
      category: 'personality',
      title: 'How my brain works',
      icon: '🧠',
      cost: 125,
      questions: [
        { id: 'bw1', q: 'How I recharge', options: ['Alone time', 'With people', 'A nap', 'A walk', 'A hobby'] },
        { id: 'bw2', q: 'What stresses me out most', open: true },
        { id: 'bw3', q: 'How I make big decisions', options: ['Gut feeling', 'Pros & cons', 'Ask everyone', 'Sleep on it', 'Overthink it'] },
        { id: 'bw4', q: 'The fastest way to cheer me up', open: true },
        { id: 'bw5', q: 'I’m most productive when it’s', options: ['Early morning', 'Afternoon', 'Late night', 'Under deadline', 'Never 😅'] },
      ],
    },
    {
      id: 'pet_peeves',
      category: 'personality',
      title: 'Pet peeves & quirks',
      icon: '😬',
      cost: 100,
      questions: [
        { id: 'pp1', q: 'A pet peeve of mine you’ve noticed', open: true },
        { id: 'pp2', q: 'My messiest area', options: ['My desk', 'My car', 'My phone tabs', 'The closet', 'I’m tidy!'] },
        { id: 'pp3', q: 'A weird quirk I have', open: true },
        { id: 'pp4', q: 'How I am when I’m hangry', options: ['Silent', 'Grumpy', 'Dramatic', 'Fine actually', 'Dangerous'] },
        { id: 'pp5', q: 'Something I’m irrationally picky about', open: true },
      ],
    },
    {
      id: 'if_i_were',
      category: 'personality',
      title: 'If I were…',
      icon: '🎭',
      cost: 100,
      questions: [
        { id: 'iw1', q: 'If I were an animal, I’d be a', options: ['Cat', 'Dog', 'Owl', 'Otter', 'Fox'] },
        { id: 'iw2', q: 'If I were a season', options: ['Spring', 'Summer', 'Autumn', 'Winter'] },
        { id: 'iw3', q: 'If I won the lottery, I’d first', open: true },
        { id: 'iw4', q: 'If I had a superpower', options: ['Teleport', 'Read minds', 'Time travel', 'Invisibility', 'Fly'] },
        { id: 'iw5', q: 'If I had a warning label, it’d say', open: true },
      ],
    },

    // ════════ FUN (+3) ════════
    {
      id: 'totally_random',
      category: 'fun',
      title: 'Totally random',
      icon: '🎲',
      cost: 100,
      questions: [
        { id: 'tr1', q: 'Pineapple on pizza?', options: ['Yes!', 'Never', 'Sometimes', 'I don’t care'] },
        { id: 'tr2', q: 'The weirdest food combo I love', open: true },
        { id: 'tr3', q: 'Cereal: milk first or cereal first?', options: ['Cereal first', 'Milk first', 'No milk', 'Dry cereal'] },
        { id: 'tr4', q: 'My useless talent', open: true },
        { id: 'tr5', q: 'Best way to spend a rainy day', options: ['Movie marathon', 'Nap', 'Cook', 'Read', 'Game'] },
      ],
    },
    {
      id: 'foodie_favorites',
      category: 'fun',
      title: 'Foodie favorites',
      icon: '🍕',
      cost: 100,
      questions: [
        { id: 'ff1', q: 'My go-to comfort food', open: true },
        { id: 'ff2', q: 'My ideal breakfast', options: ['Pancakes', 'Eggs & toast', 'Cereal', 'Fruit', 'Skip it'] },
        { id: 'ff3', q: 'A food I could eat every day', open: true },
        { id: 'ff4', q: 'Sweet or savory?', options: ['Sweet', 'Savory', 'Both', 'Depends'] },
        { id: 'ff5', q: 'My ride-or-die snack', open: true },
      ],
    },
    {
      id: 'travel_dreams',
      category: 'fun',
      title: 'Travel dreams',
      icon: '🗺️',
      cost: 125,
      questions: [
        { id: 'td1', q: 'Top of my travel bucket list', open: true },
        { id: 'td2', q: 'Beach, city, or mountains?', options: ['Beach', 'City', 'Mountains', 'Countryside'] },
        { id: 'td3', q: 'My ideal trip length', options: ['Weekend', 'A week', 'Two weeks', 'A month+'] },
        { id: 'td4', q: 'A place I’d love to take you', open: true },
        { id: 'td5', q: 'Window or aisle seat?', options: ['Window', 'Aisle', 'Middle (hero)', 'Whatever’s open'] },
      ],
    },

    // ════════ OCCASIONS (+2) ════════
    {
      id: 'holiday_traditions',
      category: 'occasions',
      title: 'Holiday traditions',
      icon: '🎄',
      cost: 125,
      questions: [
        { id: 'ht1', q: 'My favorite holiday', open: true },
        { id: 'ht2', q: 'A tradition I’d love us to start', open: true },
        { id: 'ht3', q: 'Gifts: handmade or store-bought?', options: ['Handmade', 'Store-bought', 'Experiences', 'Surprise me'] },
        { id: 'ht4', q: 'My ideal holiday vibe', options: ['Cozy & quiet', 'Big & festive', 'Travel away', 'Just us'] },
        { id: 'ht5', q: 'A holiday food I can’t skip', open: true },
      ],
    },
    {
      id: 'anniversary_feels',
      category: 'occasions',
      title: 'Anniversary feels',
      icon: '💍',
      cost: 125,
      questions: [
        { id: 'an1', q: 'Our most memorable date so far', open: true },
        { id: 'an2', q: 'How you’d want to celebrate an anniversary', options: ['Fancy dinner', 'Weekend away', 'Quiet day in', 'Recreate our first date', 'Surprise me'] },
        { id: 'an3', q: 'A moment you’d relive with me', open: true },
        { id: 'an4', q: 'A gift that says "us"', open: true },
        { id: 'an5', q: 'What you love most about how far we’ve come', open: true },
      ],
    },

    // ════════ PARTY (+5) ════════
    {
      id: 'rapid_fire_party',
      category: 'party',
      title: 'Rapid fire: this or that',
      icon: '⚡',
      cost: 100,
      format: 'party',
      questions: [
        { id: 'tot1', q: 'Pick one', options: ['Coffee', 'Tea'] },
        { id: 'tot2', q: 'Pick one', options: ['Texting', 'Calling'] },
        { id: 'tot3', q: 'Pick one', options: ['Dogs', 'Cats'] },
        { id: 'tot4', q: 'Pick one', options: ['Morning', 'Night'] },
        { id: 'tot5', q: 'Pick one', options: ['Sweet', 'Salty'] },
        { id: 'tot6', q: 'Pick one', options: ['Movies', 'Series'] },
        { id: 'tot7', q: 'Pick one', options: ['Books', 'Podcasts'] },
        { id: 'tot8', q: 'Pick one', options: ['Adventure', 'Relax'] },
      ],
    },
    {
      id: 'nhie_travel',
      category: 'party',
      title: 'Never have I ever: travel',
      icon: '✈️',
      cost: 100,
      format: 'party',
      questions: [
        { id: 'nht1', q: 'Missed a flight', options: ['I have', 'I never'] },
        { id: 'nht2', q: 'Traveled to another country', options: ['I have', 'I never'] },
        { id: 'nht3', q: 'Slept in an airport', options: ['I have', 'I never'] },
        { id: 'nht4', q: 'Gone on a road trip', options: ['I have', 'I never'] },
        { id: 'nht5', q: 'Tried food I couldn’t name', options: ['I have', 'I never'] },
        { id: 'nht6', q: 'Gotten lost in a new city', options: ['I have', 'I never'] },
      ],
    },
    {
      id: 'wyr_food',
      category: 'party',
      title: 'Would you rather: food',
      icon: '🍔',
      cost: 100,
      format: 'party',
      questions: [
        { id: 'wf1', q: 'Would you rather…', options: ['Only sweet', 'Only savory'] },
        { id: 'wf2', q: 'Would you rather…', options: ['Pizza forever', 'Tacos forever'] },
        { id: 'wf3', q: 'Would you rather…', options: ['Never coffee', 'Never dessert'] },
        { id: 'wf4', q: 'Would you rather…', options: ['Cook every meal', 'Order every meal'] },
        { id: 'wf5', q: 'Would you rather…', options: ['Spicy', 'Mild'] },
        { id: 'wf6', q: 'Would you rather…', options: ['Breakfast for dinner', 'Dinner for breakfast'] },
      ],
    },
    {
      id: 'most_likely_to',
      category: 'party',
      title: 'Most likely to…',
      icon: '🏆',
      cost: 100,
      format: 'party',
      questions: [
        { id: 'ml1', q: 'Most likely to cry at a movie', options: ['Me', 'You'] },
        { id: 'ml2', q: 'Most likely to text first', options: ['Me', 'You'] },
        { id: 'ml3', q: 'Most likely to sleep in', options: ['Me', 'You'] },
        { id: 'ml4', q: 'Most likely to plan the trip', options: ['Me', 'You'] },
        { id: 'ml5', q: 'Most likely to start a food fight', options: ['Me', 'You'] },
        { id: 'ml6', q: 'Most likely to get us lost', options: ['Me', 'You'] },
      ],
    },
    {
      id: 'hot_or_not',
      category: 'party',
      title: 'Hot or not (compare)',
      icon: '🌡️',
      cost: 100,
      format: 'party',
      questions: [
        { id: 'hn1', q: 'Surprise gifts', options: ['Hot', 'Not'] },
        { id: 'hn2', q: 'PDA in public', options: ['Hot', 'Not'] },
        { id: 'hn3', q: 'Matching outfits', options: ['Hot', 'Not'] },
        { id: 'hn4', q: 'Early morning texts', options: ['Hot', 'Not'] },
        { id: 'hn5', q: 'Cooking together', options: ['Hot', 'Not'] },
        { id: 'hn6', q: 'Long voice notes', options: ['Hot', 'Not'] },
      ],
    },

    // ════════ DEEP TALKS (+5) ════════
    {
      id: 'heart_to_heart',
      category: 'deep',
      title: 'Heart to heart',
      icon: '❤️‍🩹',
      cost: 150,
      questions: [
        { id: 'hh1', q: 'Something you’ve been afraid to tell me', open: true },
        { id: 'hh2', q: 'When do you feel most supported by me', open: true },
        { id: 'hh3', q: 'A way I could love you better', open: true },
        { id: 'hh4', q: 'What does "safe" feel like to you', open: true },
        { id: 'hh5', q: 'A wound you’re still healing', open: true },
      ],
    },
    {
      id: 'our_values',
      category: 'deep',
      title: 'Our values',
      icon: '🧭',
      cost: 150,
      questions: [
        { id: 'ov1', q: 'What matters most to you in life', options: ['Family', 'Freedom', 'Growth', 'Security', 'Adventure'] },
        { id: 'ov2', q: 'How you define a good life', open: true },
        { id: 'ov3', q: 'A value you want us to share', open: true },
        { id: 'ov4', q: 'Money: save it or spend it?', options: ['Save', 'Spend', 'Balance', 'Invest'] },
        { id: 'ov5', q: 'What does home mean to you', open: true },
      ],
    },
    {
      id: 'fears_and_dreams',
      category: 'deep',
      title: 'Fears & dreams',
      icon: '🌌',
      cost: 150,
      questions: [
        { id: 'fd1', q: 'Your biggest dream right now', open: true },
        { id: 'fd2', q: 'A fear you don’t talk about often', open: true },
        { id: 'fd3', q: 'Something you want to achieve in a year', open: true },
        { id: 'fd4', q: 'What would you do if you couldn’t fail', open: true },
        { id: 'fd5', q: 'A dream you have for us', open: true },
      ],
    },
    {
      id: 'if_were_honest',
      category: 'deep',
      title: 'If we’re honest…',
      icon: '🕯️',
      cost: 150,
      questions: [
        { id: 'ih1', q: 'Something you’ve never said out loud', open: true },
        { id: 'ih2', q: 'A time you felt really proud of yourself', open: true },
        { id: 'ih3', q: 'What you need more of from me', options: ['Reassurance', 'Space', 'Attention', 'Patience', 'Affection'] },
        { id: 'ih4', q: 'A hard truth you’ve learned about love', open: true },
        { id: 'ih5', q: 'What you’re grateful for today', open: true },
      ],
    },
    {
      id: 'growing_together',
      category: 'deep',
      title: 'Growing together',
      icon: '🌿',
      cost: 150,
      questions: [
        { id: 'gt1', q: 'How have you grown since we met', open: true },
        { id: 'gt2', q: 'Something you want us to learn together', open: true },
        { id: 'gt3', q: 'A habit you want to build', open: true },
        { id: 'gt4', q: 'Where do you see us in 5 years', open: true },
        { id: 'gt5', q: 'What keeps a relationship strong', options: ['Trust', 'Communication', 'Fun', 'Effort', 'All of it'] },
      ],
    },

    // ════════ LONG DISTANCE (+5) ════════
    {
      id: 'miles_apart',
      category: 'longdistance',
      title: 'Miles apart',
      icon: '📍',
      cost: 125,
      questions: [
        { id: 'ma1', q: 'The hardest part of being apart', open: true },
        { id: 'ma2', q: 'What helps you feel close to me', options: ['Calls', 'Texts', 'Photos', 'Voice notes', 'This app 💜'] },
        { id: 'ma3', q: 'Something small that makes the distance easier', open: true },
        { id: 'ma4', q: 'When you miss me most', options: ['Mornings', 'Meals', 'Nights', 'Good news', 'Bad days'] },
        { id: 'ma5', q: 'A way I can show up for you from afar', open: true },
      ],
    },
    {
      id: 'when_together',
      category: 'longdistance',
      title: 'When we’re together',
      icon: '🤗',
      cost: 125,
      questions: [
        { id: 'wt1', q: 'First thing you want to do when we reunite', open: true },
        { id: 'wt2', q: 'The hug or the kiss first?', options: ['Hug', 'Kiss', 'Both at once', 'Just stare 🥹'] },
        { id: 'wt3', q: 'A simple day together you’d love', open: true },
        { id: 'wt4', q: 'A food we have to share in person', open: true },
        { id: 'wt5', q: 'Where should our next visit be', options: ['Your place', 'My place', 'Somewhere new', 'Halfway'] },
      ],
    },
    {
      id: 'virtual_date_night',
      category: 'longdistance',
      title: 'Virtual date night',
      icon: '💻',
      cost: 100,
      questions: [
        { id: 'vd1', q: 'Best virtual date we could do', options: ['Movie sync', 'Cook same meal', 'Online game', 'Just talk', 'Stargaze on call'] },
        { id: 'vd2', q: 'A show we should watch together apart', open: true },
        { id: 'vd3', q: 'Ideal call length', options: ['Quick check-in', '30 min', 'An hour', 'Fall asleep on call'] },
        { id: 'vd4', q: 'A game we could play over call', open: true },
        { id: 'vd5', q: 'Camera on or just voice?', options: ['Camera on', 'Just voice', 'Depends on the day'] },
      ],
    },
    {
      id: 'i_miss_your',
      category: 'longdistance',
      title: 'I miss your…',
      icon: '💭',
      cost: 100,
      questions: [
        { id: 'im1', q: 'The thing about me you miss most', open: true },
        { id: 'im2', q: 'My laugh, my voice, or my hugs?', options: ['Laugh', 'Voice', 'Hugs', 'All of it'] },
        { id: 'im3', q: 'A moment with me you replay', open: true },
        { id: 'im4', q: 'What you’d do if I were there right now', open: true },
        { id: 'im5', q: 'A photo of us you love', open: true },
      ],
    },
    {
      id: 'counting_down',
      category: 'longdistance',
      title: 'Counting down',
      icon: '⏳',
      cost: 100,
      questions: [
        { id: 'cd1', q: 'How you cope while we count down', open: true },
        { id: 'cd2', q: 'A milestone you’re looking forward to', open: true },
        { id: 'cd3', q: 'What gets you through a tough week apart', open: true },
        { id: 'cd4', q: 'One day, I hope we', open: true },
        { id: 'cd5', q: 'Distance is worth it because', open: true },
      ],
    },

    // ════════ SPICY 🌶️ (+6) ════════
    {
      id: 'spicy_truth_or_dare',
      category: 'spicy',
      title: 'Truth or dare: spicy',
      icon: '🌶️',
      cost: 150,
      premium: true,
      format: 'party',
      questions: [
        { id: 'std1', q: 'Lights on or off?', options: ['On', 'Off'] },
        { id: 'std2', q: 'Slow & sweet or bold?', options: ['Slow', 'Bold'] },
        { id: 'std3', q: 'Tease or be teased?', options: ['Tease', 'Be teased'] },
        { id: 'std4', q: 'Morning or midnight?', options: ['Morning', 'Midnight'] },
        { id: 'std5', q: 'Whisper or no words?', options: ['Whisper', 'No words'] },
        { id: 'std6', q: 'Plan it or spontaneous?', options: ['Plan it', 'Spontaneous'] },
      ],
    },
    {
      id: 'wyr_spicy',
      category: 'spicy',
      title: 'Would you rather: spicy',
      icon: '😏',
      cost: 150,
      format: 'party',
      questions: [
        { id: 'wsp1', q: 'Would you rather…', options: ['Long kiss', 'Long cuddle'] },
        { id: 'wsp2', q: 'Would you rather…', options: ['Be little spoon', 'Be big spoon'] },
        { id: 'wsp3', q: 'Would you rather…', options: ['Neck kisses', 'Back scratches'] },
        { id: 'wsp4', q: 'Would you rather…', options: ['Shower together', 'Bath together'] },
        { id: 'wsp5', q: 'Would you rather…', options: ['Slow dance', 'Make out'] },
        { id: 'wsp6', q: 'Would you rather…', options: ['Be in control', 'Let go'] },
      ],
    },
    {
      id: 'nhie_spicy',
      category: 'spicy',
      title: 'Never have I ever: spicy',
      icon: '🔥',
      cost: 150,
      format: 'party',
      questions: [
        { id: 'nsp1', q: 'Sent a flirty text today', options: ['I have', 'I never'] },
        { id: 'nsp2', q: 'Had a crush on a stranger', options: ['I have', 'I never'] },
        { id: 'nsp3', q: 'Kissed in the rain', options: ['I have', 'I never'] },
        { id: 'nsp4', q: 'Made the first move', options: ['I have', 'I never'] },
        { id: 'nsp5', q: 'Daydreamed about you today', options: ['I have', 'I never'] },
        { id: 'nsp6', q: 'Blushed because of you', options: ['I have', 'I never'] },
      ],
    },
    {
      id: 'your_turn_ons',
      category: 'spicy',
      title: 'Your turn-ons',
      icon: '💋',
      cost: 175,
      premium: true,
      questions: [
        { id: 'yt1', q: 'A trait that instantly draws you in', options: ['Confidence', 'Humor', 'Kindness', 'Mystery', 'A great smile'] },
        { id: 'yt2', q: 'My most attractive feature', open: true },
        { id: 'yt3', q: 'A whispered word or phrase that gets you', open: true },
        { id: 'yt4', q: 'Where you love to be kissed', options: ['Lips', 'Neck', 'Forehead', 'Shoulder', 'Hands'] },
        { id: 'yt5', q: 'Something I do that drives you wild', open: true },
      ],
    },
    {
      id: 'fantasy_island',
      category: 'spicy',
      title: 'Fantasy island',
      icon: '🏝️',
      cost: 175,
      premium: true,
      questions: [
        { id: 'fi_1', q: 'Our dream romantic getaway', open: true },
        { id: 'fi_2', q: 'A fantasy date setting', options: ['Beach at night', 'Cabin in the snow', 'City hotel', 'Under the stars', 'Private island'] },
        { id: 'fi_3', q: 'Something daring you’d try with me', open: true },
        { id: 'fi_4', q: 'Slow weekend or wild adventure?', options: ['Slow weekend', 'Wild adventure', 'Both in one'] },
        { id: 'fi_5', q: 'A secret wish you’d tell only me', open: true },
      ],
    },
    {
      id: 'after_dark_qa',
      category: 'spicy',
      title: 'After dark Q&A',
      icon: '🌙',
      cost: 175,
      premium: true,
      questions: [
        { id: 'ad1', q: 'What were you thinking the first time we kissed', open: true },
        { id: 'ad2', q: 'Cuddle, talk, or sleep after?', options: ['Cuddle', 'Talk', 'Sleep', 'All three'] },
        { id: 'ad3', q: 'A compliment you’ve been holding back', open: true },
        { id: 'ad4', q: 'What makes you feel desired', open: true },
        { id: 'ad5', q: 'A late-night confession', open: true },
      ],
    },
  ],
};

