// server/party-data.js — Truth or Dare prompt deck (couple-friendly).
module.exports = {
  truths: [
    'What was your first impression of me?',
    'What is one thing I do that always makes you smile?',
    'What is a tiny fear you have never told me?',
    "What's your favorite memory of us so far?",
    'What is something you want us to try together?',
    'When did you first feel butterflies about me?',
    'What is a habit of mine you secretly find cute?',
    "What's a compliment you've been wanting to give me?",
    'What is your love language, really?',
    'What song reminds you of me?',
    'What is something small I could do that would mean a lot?',
    'What is a dream you have for us?',
    "What's the most thoughtful thing I've done for you?",
    'What makes you feel safest with me?',
    'What is a place you would love us to wake up in?',
  ],
  dares: [
    'Send me your favorite selfie right now.',
    'Give me a 10-second hug (or describe one in detail).',
    'Do your best impression of me.',
    'Text me three things you love about me.',
    'Make up a short rhyme about us.',
    'Show me the last photo in your camera roll.',
    'Plan our next date in one sentence.',
    'Sing one line of “our” song.',
    'Give me a genuine compliment in a silly voice.',
    'Recreate our first date emoji-only.',
    'Do a little happy dance for 5 seconds.',
    'Whisper (or type) your favorite pet name for me.',
    'Draw a tiny heart somewhere and show me.',
    'Tell me a secret you have never told anyone.',
    'Give me a forehead kiss (or a 😘).',
  ],
};
